Fsync is now more customizable.

diff --git a/fsync b/fsync
--- a/fsync
+++ b/fsync
@@ -1,13 +1,23 @@
 #!/bin/bash
 
-flash_dir="$FLASH_ROOT/flash/"
-sync_dir="$HOME/flash/"
-n="";
+target=$1
+options=${@:2}
 
-if [ -z $FLASH_ROOT ]; then echo "\$FLASH_ROOT is empty."; exit; fi
-if [ ! -d $flash_dir ]; then echo "$flash_dir not found."; exit; fi
+function sync() {
+	from=$1; to=$2; options=${@:3}
 
-if [ ! -d $sync_dir ]; then mkdir -p $sync_dir; fi
-if [ "$1" = "-n" ]; then n="n"; fi
+	if [ ! -d "$from" ]; then echo "$from is not found."; exit 1; fi
 
-rsync -av$n --delete $flash_dir $sync_dir;
+	mkdir -p $to
+	rsync -av $options $from $to
+}
+
+if [ -z "$target" ]; then echo "$usage"; exit 1; fi
+if [ -z "$FLASH_ROOT" ]; then echo "\$FLASH_ROOT is empty."; exit 1; fi
+
+case "$target" in
+	ssh) sync $HOME/.ssh/ $FLASH_ROOT/flash/ssh/ --delete $options ;;
+	docs) sync $HOME/Documents/ $FLASH_ROOT/flash/docs/ --delete $options ;;
+
+	*) sync $FLASH_ROOT/flash/ $HOME/flash/ --delete $options ;;
+esac
