Add check for flash root existence.

diff --git a/fsync b/fsync
--- a/fsync
+++ b/fsync
@@ -35,11 +35,12 @@ for ((i=0;++i<=$#;)); do
 done
 
 if [ -z "$FLASH_ROOT" ]; then echo "\$FLASH_ROOT is empty."; exit 1; fi
+if [ ! -d "$FLASH_ROOT" ]; then echo "$FLASH_ROOT is not found."; exit 1; fi
 if [ -n "$help" ]; then echo "$man"; exit 0; fi
 
 case "$target" in
 	ssh) $command $HOME/.ssh/ $FLASH_ROOT/flash/ssh/ $n ;;
-	git) $command dogit:/home/git/ $FLASH_ROOT/flash/git/ $n ;;
+	git) $command git:git/ $FLASH_ROOT/flash/git/ $n ;;
 	docs) $command $HOME/Documents/ $FLASH_ROOT/flash/docs/ $n ;;
 	*) $command $FLASH_ROOT/flash/ $HOME/flash/ $n ;;
 esac
